//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActStatus
    {
        public ActStatus()
        {
            this.WORK_ACTS = new HashSet<WORK_ACTS>();
        }
    
        public int ID_status { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<WORK_ACTS> WORK_ACTS { get; set; }
    }
}
