//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.PRODUCTION_ASSETS = new HashSet<PRODUCTION_ASSETS>();
        }
    
        public int ID_category { get; set; }
        public string Category1 { get; set; }
    
        public virtual ICollection<PRODUCTION_ASSETS> PRODUCTION_ASSETS { get; set; }
    }
}
