//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLETION_ACTS
    {
        public int id { get; set; }
        public string act_number { get; set; }
        public Nullable<int> work_act_id { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public Nullable<int> supervisor_id { get; set; }
        public Nullable<bool> quality_check { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual MASTERS MASTERS { get; set; }
        public virtual WORK_ACTS WORK_ACTS { get; set; }
    }
}
