//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        public EQUIPMENT()
        {
            this.EQUIPMENT_PURCHASES = new HashSet<EQUIPMENT_PURCHASES>();
            this.MAINTENANCE = new HashSet<MAINTENANCE>();
            this.WORK_ACTS = new HashSet<WORK_ACTS>();
        }
    
        public int ID { get; set; }
        public string asset_id { get; set; }
        public string equipment_type { get; set; }
        public string manufacturer { get; set; }
        public Nullable<System.DateTime> installation_date { get; set; }
        public Nullable<int> Workshop_id { get; set; }
        public Nullable<int> warranty_period_months { get; set; }
        public Nullable<System.DateTime> last_maintenance_date { get; set; }
        public Nullable<System.DateTime> next_maintenance_date { get; set; }
        public string operational_status { get; set; }
        public Nullable<int> assigned_to { get; set; }
        public Nullable<int> current_work_hours { get; set; }
        public Nullable<int> max_work_hours_before_maintenance { get; set; }
        public Nullable<int> status { get; set; }
        public string notes { get; set; }
    
        public virtual MASTERS MASTERS { get; set; }
        public virtual STATUSASSETS STATUSASSETS { get; set; }
        public virtual WORKSHOPS WORKSHOPS { get; set; }
        public virtual ICollection<EQUIPMENT_PURCHASES> EQUIPMENT_PURCHASES { get; set; }
        public virtual ICollection<MAINTENANCE> MAINTENANCE { get; set; }
        public virtual ICollection<WORK_ACTS> WORK_ACTS { get; set; }
    }
}
