//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT_PURCHASES
    {
        public int id { get; set; }
        public string purchase_number { get; set; }
        public Nullable<int> asset_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> expected_delivery { get; set; }
        public Nullable<System.DateTime> actual_delivery { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> purchase_manager_id { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual MASTERS MASTERS { get; set; }
        public virtual STATUS_PURCHASE STATUS_PURCHASE { get; set; }
        public virtual SUPPLIERS SUPPLIERS { get; set; }
    }
}
