//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINISHED_PRODUCTS
    {
        public int ID { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string description { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string warehouse_location { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Unit Unit1 { get; set; }
    }
}
