//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINTENANCE
    {
        public int id { get; set; }
        public Nullable<int> equipment_id { get; set; }
        public Nullable<System.DateTime> maintenance_date { get; set; }
        public string maintenance_type { get; set; }
        public Nullable<int> technician_id { get; set; }
        public string description { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> downtime_hours { get; set; }
        public string parts_replaced { get; set; }
        public Nullable<System.DateTime> next_maintenance_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual STATUSASSETS STATUSASSETS { get; set; }
        public virtual MASTERS MASTERS { get; set; }
    }
}
