//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERS
    {
        public MASTERS()
        {
            this.COMPLETION_ACTS = new HashSet<COMPLETION_ACTS>();
            this.EQUIPMENT = new HashSet<EQUIPMENT>();
            this.EQUIPMENT_PURCHASES = new HashSet<EQUIPMENT_PURCHASES>();
            this.MAINTENANCE = new HashSet<MAINTENANCE>();
            this.REPORTS = new HashSet<REPORTS>();
            this.WORK_ACTS = new HashSet<WORK_ACTS>();
            this.WORKSHOPS = new HashSet<WORKSHOPS>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> specialty { get; set; }
        public string skill_level { get; set; }
        public Nullable<int> qualifications { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<bool> is_available { get; set; }
    
        public virtual ICollection<COMPLETION_ACTS> COMPLETION_ACTS { get; set; }
        public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; }
        public virtual ICollection<EQUIPMENT_PURCHASES> EQUIPMENT_PURCHASES { get; set; }
        public virtual ICollection<MAINTENANCE> MAINTENANCE { get; set; }
        public virtual QUALIFICATION QUALIFICATION { get; set; }
        public virtual SPECIALTY SPECIALTY1 { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual ICollection<REPORTS> REPORTS { get; set; }
        public virtual ICollection<WORK_ACTS> WORK_ACTS { get; set; }
        public virtual ICollection<WORKSHOPS> WORKSHOPS { get; set; }
    }
}
