//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_ASSETS
    {
        public PRODUCTION_ASSETS()
        {
            this.WORK_ACTS_MATERIALS = new HashSet<WORK_ACTS_MATERIALS>();
            this.WORK_ACTS = new HashSet<WORK_ACTS>();
        }
    
        public int id { get; set; }
        public Nullable<int> asset_type { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> min_quantity { get; set; }
        public string warehouse_location { get; set; }
        public Nullable<int> workshop_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<decimal> purchase_cost { get; set; }
        public Nullable<decimal> current_value { get; set; }
        public Nullable<int> status { get; set; }
        public string serial_number { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ASSETTYPE ASSETTYPE { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual STATUSASSETS STATUSASSETS { get; set; }
        public virtual SUPPLIERS SUPPLIERS { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual WORKSHOPS WORKSHOPS { get; set; }
        public virtual ICollection<WORK_ACTS_MATERIALS> WORK_ACTS_MATERIALS { get; set; }
        public virtual ICollection<WORK_ACTS> WORK_ACTS { get; set; }
    }
}
