//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALIFICATION
    {
        public QUALIFICATION()
        {
            this.MASTERS = new HashSet<MASTERS>();
        }
    
        public int ID_Qualification { get; set; }
        public string Qualification1 { get; set; }
    
        public virtual ICollection<MASTERS> MASTERS { get; set; }
    }
}
