//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTS
    {
        public int id { get; set; }
        public string report_type { get; set; }
        public Nullable<System.DateTime> period_start { get; set; }
        public Nullable<System.DateTime> period_end { get; set; }
        public Nullable<int> generated_by { get; set; }
        public string report_data { get; set; }
        public string file_path { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual MASTERS MASTERS { get; set; }
    }
}
