//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALTY
    {
        public SPECIALTY()
        {
            this.MASTERS = new HashSet<MASTERS>();
        }
    
        public int ID_specialty { get; set; }
        public string Speciality { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<MASTERS> MASTERS { get; set; }
    }
}
