//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_PURCHASE
    {
        public STATUS_PURCHASE()
        {
            this.EQUIPMENT_PURCHASES = new HashSet<EQUIPMENT_PURCHASES>();
        }
    
        public int ID_status { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<EQUIPMENT_PURCHASES> EQUIPMENT_PURCHASES { get; set; }
    }
}
