//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUSASSETS
    {
        public STATUSASSETS()
        {
            this.EQUIPMENT = new HashSet<EQUIPMENT>();
            this.MAINTENANCE = new HashSet<MAINTENANCE>();
            this.PRODUCTION_ASSETS = new HashSet<PRODUCTION_ASSETS>();
        }
    
        public int ID_status { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; }
        public virtual ICollection<MAINTENANCE> MAINTENANCE { get; set; }
        public virtual ICollection<PRODUCTION_ASSETS> PRODUCTION_ASSETS { get; set; }
    }
}
