//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIERS
    {
        public SUPPLIERS()
        {
            this.EQUIPMENT_PURCHASES = new HashSet<EQUIPMENT_PURCHASES>();
            this.PRODUCTION_ASSETS = new HashSet<PRODUCTION_ASSETS>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string contact_person { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string tax_number { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ICollection<EQUIPMENT_PURCHASES> EQUIPMENT_PURCHASES { get; set; }
        public virtual ICollection<PRODUCTION_ASSETS> PRODUCTION_ASSETS { get; set; }
    }
}
