//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.FINISHED_PRODUCTS = new HashSet<FINISHED_PRODUCTS>();
            this.PRODUCTION_ASSETS = new HashSet<PRODUCTION_ASSETS>();
        }
    
        public int ID { get; set; }
        public string unit1 { get; set; }
        public Nullable<decimal> quantity { get; set; }
    
        public virtual ICollection<FINISHED_PRODUCTS> FINISHED_PRODUCTS { get; set; }
        public virtual ICollection<PRODUCTION_ASSETS> PRODUCTION_ASSETS { get; set; }
    }
}
