//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.MASTERS = new HashSet<MASTERS>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ICollection<MASTERS> MASTERS { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
