//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOGS
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string action_type { get; set; }
        public string entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public string description { get; set; }
        public string ip_address { get; set; }
        public string user_agent { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
