//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSHOPS
    {
        public WORKSHOPS()
        {
            this.EQUIPMENT = new HashSet<EQUIPMENT>();
            this.PRODUCTION_ASSETS = new HashSet<PRODUCTION_ASSETS>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public Nullable<int> manager_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; }
        public virtual MASTERS MASTERS { get; set; }
        public virtual ICollection<PRODUCTION_ASSETS> PRODUCTION_ASSETS { get; set; }
    }
}
