//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_ACTS_MATERIALS
    {
        public int id { get; set; }
        public Nullable<int> work_act_id { get; set; }
        public Nullable<int> asset_id { get; set; }
        public Nullable<decimal> quantity_used { get; set; }
    
        public virtual PRODUCTION_ASSETS PRODUCTION_ASSETS { get; set; }
        public virtual WORK_ACTS WORK_ACTS { get; set; }
    }
}
