//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssets.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_ACTS
    {
        public WORK_ACTS()
        {
            this.COMPLETION_ACTS = new HashSet<COMPLETION_ACTS>();
            this.WORK_ACTS_MATERIALS = new HashSet<WORK_ACTS_MATERIALS>();
        }
    
        public int id { get; set; }
        public string act_number { get; set; }
        public Nullable<System.DateTime> work_date { get; set; }
        public Nullable<int> master_id { get; set; }
        public string work_type { get; set; }
        public Nullable<int> equipment_id { get; set; }
        public Nullable<int> asset_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ActStatus ActStatus { get; set; }
        public virtual ICollection<COMPLETION_ACTS> COMPLETION_ACTS { get; set; }
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual MASTERS MASTERS { get; set; }
        public virtual PRODUCTION_ASSETS PRODUCTION_ASSETS { get; set; }
        public virtual ICollection<WORK_ACTS_MATERIALS> WORK_ACTS_MATERIALS { get; set; }
    }
}
